import {
    AlertTriangle,
    ArrowDown,
    ArrowRight,
    ArrowUp,
    ArrowUpDown,
    BriefcaseBusiness,
    Calendar,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Construction,
    DollarSign,
    Dot,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    Gem,
    Globe,
    Home,
    Info,
    Instagram,
    Key,
    LayoutDashboard,
    LifeBuoy,
    Link,
    Loader2,
    LogIn,
    LogOut,
    Mail,
    MapPin,
    Menu,
    MoreHorizontal,
    PersonStanding,
    Plus,
    Search,
    SlidersHorizontal,
    Trash,
    Twitter,
    User,
    Users,
    X,
    Youtube,
    type IconNode as LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
    trash: Trash,
    arrowRight: ArrowRight,
    search: Search,
    globe: Globe,
    link: Link,
    mail: Mail,
    dollar: DollarSign,
    key: Key,
    plus: Plus,
    moreHor: MoreHorizontal,
    sliderHor: SlidersHorizontal,
    arrowDown: ArrowDown,
    arrowUp: ArrowUp,
    arrowUpDown: ArrowUpDown,
    briefcaseBusiness: BriefcaseBusiness,
    personStanding: PersonStanding,
    users: Users,
    calendar: Calendar,
    mapPin: MapPin,
    construction: Construction,
    home: Home,
    dashboard: LayoutDashboard,
    logout: LogOut,
    user: User,
    menu: Menu,
    externalLink: ExternalLink,
    dot: Dot,
    check: Check,
    cross: X,
    hide: EyeOff,
    view: Eye,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    spinner: Loader2,
    warning: AlertTriangle,
    login: LogIn,
    briefcase: BriefcaseBusiness,
    diamond: Gem,
    lifeBuoy: LifeBuoy,
    info: Info,
    facebook: Facebook,
    twitter: Twitter,
    youtube: Youtube,
    instagram: Instagram,
};
